In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("customer_segmentation_data.csv")

In [4]:
df.head()

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
0,1,38,Female,99342,90,3,24,Groceries,113.53
1,2,21,Female,78852,60,2,42,Sports,41.93
2,3,60,Female,126573,30,2,28,Clothing,424.36
3,4,40,Other,47099,74,9,5,Home & Garden,991.93
4,5,65,Female,140621,21,3,25,Electronics,347.08

In [5]:
df.tail()

,id,age,gender,income,spending_score,membership_years,purchase_frequency,preferred_category,last_purchase_amount
995,996,57,Male,112170,57,6,1,Clothing,313.64
996,997,23,Other,65337,76,10,23,Groceries,632.83
997,998,23,Male,113097,40,5,42,Sports,75.09
998,999,22,Female,113695,63,7,44,Electronics,505.16
999,1000,36,Female,90420,7,2,31,Groceries,669.26

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1000 non-null   int64
 1   age                   1000 non-null   int64
 2   gender                1000 non-null   object
 3   income                1000 non-null   int64
 4   spending_score        1000 non-null   int64
 5   membership_years      1000 non-null   int64
 6   purchase_frequency    1000 non-null   int64
 7   preferred_category    1000 non-null   object
 8   last_purchase_amount  1000 non-null   float64
dtypes: float64(1), int64(6), object(2)
memory usage: 70.4+ KB

In [7]:
df.isnull().sum()

id                      0
age                     0
gender                  0
income                  0
spending_score          0
membership_years        0
purchase_frequency      0
preferred_category      0
last_purchase_amount    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.columns

Index(['id', 'age', 'gender', 'income', 'spending_score', 'membership_years',
       'purchase_frequency', 'preferred_category', 'last_purchase_amount'],
      dtype='object')

In [12]:
categorical_columns = df.select_dtypes(include=['object']).columns
print(categorical_columns)

Index(['gender', 'preferred_category'], dtype='object')

In [13]:
categorical_rows = df[categorical_columns]
print(categorical_rows)

     gender preferred_category
0    Female          Groceries
1    Female             Sports
2    Female           Clothing
3     Other      Home & Garden
4    Female        Electronics
..      ...                ...
995    Male           Clothing
996   Other          Groceries
997    Male             Sports
998  Female        Electronics
999  Female          Groceries

[1000 rows x 2 columns]

In [14]:
df.to_csv("customer_segementation_data.csv", index=False)

In [17]:
from google.colab import files

files.download("customer_segementation_data.csv")